<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Film;
use App\Room;
use App\Schedule;
use App\Cinema;
use App\Client;
use App\Ticket;
use DB;
use View;
use Illuminate\Support\Facades\Auth;

class BookingController extends Controller
{
    public function index( $cinema_id, $room_id, $schedule_id, $film_id, $cinema_name, 
                            $room_name, $seat_left, $total_seat, $start_time,
                            $end_time){
        
        $date = date('d/m/Y',$start_time);
        $f = Film::find($film_id);
        
        $seat = Room::find($room_id)->seat()->get();
        $seat_taken = Schedule::find($schedule_id)->seat()->get();
        
        $map = array(
            1 => array(
                15 => 1,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            2 => array(
                15 => 1,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            3 => array(
                15 => 0,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            4 => array(
                15 => 0,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            5 => array(
                15 => 1,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            6 => array(
                15 => 1,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            7 => array(
                15 => 1,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            8 => array(
                15 => 1,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            9 => array(
                15 => 1,
                14 => 1,
                13 => 0,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 0,
                2 => 1,
                1 => 1,
            ),
            10 => array(
                15 => 0,
                14 => 1,
                13 => 1,
                12 => 1,
                11 => 1,
                10 => 1,
                9 => 1,
                8 => 1,
                7 => 1,
                6 => 1,
                5 => 1,
                4 => 1,
                3 => 1,
                2 => 1,
                1 => 1,
            ),
        );

        $map_type = array(
            1 => array(
                15 => 'standard',
                14 => 'standard',
                13 => 0,
                12 => 'standard',
                11 => 'standard',
                10 => 'standard',
                9 => 'standard',
                8 => 'standard',
                7 => 'standard',
                6 => 'standard',
                5 => 'standard',
                4 => 'standard',
                3 => 0,
                2 => 'standard',
                1 => 'standard',
            ),
            2 => array(
                15 => 'standard',
                14 => 'standard',
                13 => 0,
                12 => 'standard',
                11 => 'standard',
                10 => 'standard',
                9 => 'standard',
                8 => 'standard',
                7 => 'standard',
                6 => 'standard',
                5 => 'standard',
                4 => 'standard',
                3 => 0,
                2 => 'standard',
                1 => 'standard',
            ),
            3 => array(
                15 => 0,
                14 => 'standard',
                13 => 0,
                12 => 'standard',
                11 => 'standard',
                10 => 'standard',
                9 => 'standard',
                8 => 'standard',
                7 => 'standard',
                6 => 'standard',
                5 => 'standard',
                4 => 'standard',
                3 => 0,
                2 => 'standard',
                1 => 'standard',
            ),
            4 => array(
                15 => 0,
                14 => 'standard',
                13 => 0,
                12 => 'standard',
                11 => 'standard',
                10 => 'standard',
                9 => 'standard',
                8 => 'standard',
                7 => 'standard',
                6 => 'standard',
                5 => 'standard',
                4 => 'standard',
                3 => 0,
                2 => 'standard',
                1 => 'standard',
            ),
            5 => array(
                15 => 'vipprime',
                14 => 'vipprime',
                13 => 0,
                12 => 'vipprime',
                11 => 'vipprime',
                10 => 'vipprime',
                9 => 'vipprime',
                8 => 'vipprime',
                7 => 'vipprime',
                6 => 'vipprime',
                5 => 'vipprime',
                4 => 'vipprime',
                3 => 0,
                2 => 'vipprime',
                1 => 'vipprime',
            ),
            6 => array(
                15 => 'vipprime',
                14 => 'vipprime',
                13 => 0,
                12 => 'vipprime',
                11 => 'vipprime',
                10 => 'vipprime',
                9 => 'vipprime',
                8 => 'vipprime',
                7 => 'vipprime',
                6 => 'vipprime',
                5 => 'vipprime',
                4 => 'vipprime',
                3 => 0,
                2 => 'vipprime',
                1 => 'vipprime',
            ),
            7 => array(
                15 => 'vipprime',
                14 => 'vipprime',
                13 => 0,
                12 => 'vipprime',
                11 => 'vipprime',
                10 => 'vipprime',
                9 => 'vipprime',
                8 => 'vipprime',
                7 => 'vipprime',
                6 => 'vipprime',
                5 => 'vipprime',
                4 => 'vipprime',
                3 => 0,
                2 => 'vipprime',
                1 => 'vipprime',
            ),
            8 => array(
                15 => 'vipprime',
                14 => 'vipprime',
                13 => 0,
                12 => 'vipprime',
                11 => 'vipprime',
                10 => 'vipprime',
                9 => 'vipprime',
                8 => 'vipprime',
                7 => 'vipprime',
                6 => 'vipprime',
                5 => 'vipprime',
                4 => 'vipprime',
                3 => 0,
                2 => 'vipprime',
                1 => 'vipprime',
            ),
            9 => array(
                15 => 'vipprime',
                14 => 'vipprime',
                13 => 0,
                12 => 'vipprime',
                11 => 'vipprime',
                10 => 'vipprime',
                9 => 'vipprime',
                8 => 'vipprime',
                7 => 'vipprime',
                6 => 'vipprime',
                5 => 'vipprime',
                4 => 'vipprime',
                3 => 0,
                2 => 'vipprime',
                1 => 'vipprime',
            ),
            10 => array(
                15 => 0,
                14 => 'sw',
                13 => 'sw',
                12 => 'sw',
                11 => 'sw',
                10 => 'sw',
                9 => 'sw',
                8 => 'sw',
                7 => 'sw',
                6 => 'sw',
                5 => 'sw',
                4 => 'sw',
                3 => 'sw',
                2 => 'sw',
                1 => 'sw',
            ),
        );
        return view('booking', compact('f','seat','seat_taken','map','map_type', 
                    'cinema_name', 'room_name', 'seat_left', 'total_seat', 'schedule_id',
                    'start_time', 'end_time', 'date'));
    }

}
